/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.enigma.ui.internal.EnigmaActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ENIGMAExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(EnigmaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		EnigmaActivator activator = EnigmaActivator.getInstance();
		return activator != null ? activator.getInjector(EnigmaActivator.FR_N7_ENIGMA) : null;
	}

}
