/**
 * generated by Xtext 2.23.0
 */
package fr.n7.eNIGMA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chemin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Chemin#getPrecedent <em>Precedent</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Chemin#getSuivant <em>Suivant</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getChemin()
 * @model
 * @generated
 */
public interface Chemin extends EObject
{
  /**
   * Returns the value of the '<em><b>Precedent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precedent</em>' reference.
   * @see #setPrecedent(Lieu)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getChemin_Precedent()
   * @model
   * @generated
   */
  Lieu getPrecedent();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Chemin#getPrecedent <em>Precedent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precedent</em>' reference.
   * @see #getPrecedent()
   * @generated
   */
  void setPrecedent(Lieu value);

  /**
   * Returns the value of the '<em><b>Suivant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Suivant</em>' reference.
   * @see #setSuivant(Lieu)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getChemin_Suivant()
   * @model
   * @generated
   */
  Lieu getSuivant();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Chemin#getSuivant <em>Suivant</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Suivant</em>' reference.
   * @see #getSuivant()
   * @generated
   */
  void setSuivant(Lieu value);

} // Chemin
