/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choix</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Choix#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Choix#getReponses <em>Reponses</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Choix#getConditions <em>Conditions</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getChoix()
 * @model
 * @generated
 */
public interface Choix extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getChoix_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Choix#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Reponses</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.eNIGMA.Reponse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reponses</em>' containment reference list.
   * @see fr.n7.eNIGMA.ENIGMAPackage#getChoix_Reponses()
   * @model containment="true"
   * @generated
   */
  EList<Reponse> getReponses();

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' reference list.
   * The list contents are of type {@link fr.n7.eNIGMA.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' reference list.
   * @see fr.n7.eNIGMA.ENIGMAPackage#getChoix_Conditions()
   * @model
   * @generated
   */
  EList<Condition> getConditions();

} // Choix
