/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Condition#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Condition#getObjetsRequis <em>Objets Requis</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Condition#getConnaissancesRequises <em>Connaissances Requises</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getCondition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Condition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Objets Requis</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.eNIGMA.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets Requis</em>' containment reference list.
   * @see fr.n7.eNIGMA.ENIGMAPackage#getCondition_ObjetsRequis()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjetsRequis();

  /**
   * Returns the value of the '<em><b>Connaissances Requises</b></em>' reference list.
   * The list contents are of type {@link fr.n7.eNIGMA.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissances Requises</em>' reference list.
   * @see fr.n7.eNIGMA.ENIGMAPackage#getCondition_ConnaissancesRequises()
   * @model
   * @generated
   */
  EList<Connaissance> getConnaissancesRequises();

} // Condition
