/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connaissance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Connaissance#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Connaissance#getQualification <em>Qualification</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Connaissance#getEtatv <em>Etatv</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Connaissance#getEtatp <em>Etatp</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getConnaissance()
 * @model
 * @generated
 */
public interface Connaissance extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getConnaissance_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Connaissance#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Qualification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualification</em>' containment reference.
   * @see #setQualification(Qualification)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getConnaissance_Qualification()
   * @model containment="true"
   * @generated
   */
  Qualification getQualification();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Connaissance#getQualification <em>Qualification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qualification</em>' containment reference.
   * @see #getQualification()
   * @generated
   */
  void setQualification(Qualification value);

  /**
   * Returns the value of the '<em><b>Etatv</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.eNIGMA.EtatVisibilite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Etatv</em>' attribute.
   * @see fr.n7.eNIGMA.EtatVisibilite
   * @see #setEtatv(EtatVisibilite)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getConnaissance_Etatv()
   * @model
   * @generated
   */
  EtatVisibilite getEtatv();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Connaissance#getEtatv <em>Etatv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Etatv</em>' attribute.
   * @see fr.n7.eNIGMA.EtatVisibilite
   * @see #getEtatv()
   * @generated
   */
  void setEtatv(EtatVisibilite value);

  /**
   * Returns the value of the '<em><b>Etatp</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.eNIGMA.EtatPossession}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Etatp</em>' attribute.
   * @see fr.n7.eNIGMA.EtatPossession
   * @see #setEtatp(EtatPossession)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getConnaissance_Etatp()
   * @model
   * @generated
   */
  EtatPossession getEtatp();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Connaissance#getEtatp <em>Etatp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Etatp</em>' attribute.
   * @see fr.n7.eNIGMA.EtatPossession
   * @see #getEtatp()
   * @generated
   */
  void setEtatp(EtatPossession value);

} // Connaissance
