/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Interaction#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Interaction#getChoix <em>Choix</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Interaction#getChoixFin <em>Choix Fin</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getInteraction()
 * @model
 * @generated
 */
public interface Interaction extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getInteraction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Interaction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Choix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix</em>' containment reference.
   * @see #setChoix(Choix)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getInteraction_Choix()
   * @model containment="true"
   * @generated
   */
  Choix getChoix();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Interaction#getChoix <em>Choix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Choix</em>' containment reference.
   * @see #getChoix()
   * @generated
   */
  void setChoix(Choix value);

  /**
   * Returns the value of the '<em><b>Choix Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix Fin</em>' containment reference.
   * @see #setChoixFin(Choix)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getInteraction_ChoixFin()
   * @model containment="true"
   * @generated
   */
  Choix getChoixFin();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Interaction#getChoixFin <em>Choix Fin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Choix Fin</em>' containment reference.
   * @see #getChoixFin()
   * @generated
   */
  void setChoixFin(Choix value);

} // Interaction
