/**
 * generated by Xtext 2.23.0
 */
package fr.n7.eNIGMA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jeu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Jeu#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Jeu#getTerritoire <em>Territoire</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Jeu#getJoueur <em>Joueur</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getJeu()
 * @model
 * @generated
 */
public interface Jeu extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getJeu_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Jeu#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Territoire</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Territoire</em>' containment reference.
   * @see #setTerritoire(Territoire)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getJeu_Territoire()
   * @model containment="true"
   * @generated
   */
  Territoire getTerritoire();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Jeu#getTerritoire <em>Territoire</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Territoire</em>' containment reference.
   * @see #getTerritoire()
   * @generated
   */
  void setTerritoire(Territoire value);

  /**
   * Returns the value of the '<em><b>Joueur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Joueur</em>' containment reference.
   * @see #setJoueur(Joueur)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getJeu_Joueur()
   * @model containment="true"
   * @generated
   */
  Joueur getJoueur();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Jeu#getJoueur <em>Joueur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Joueur</em>' containment reference.
   * @see #getJoueur()
   * @generated
   */
  void setJoueur(Joueur value);

} // Jeu
