/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Joueur</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Joueur#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Joueur#getLimite <em>Limite</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Joueur#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Joueur#getConnaissances <em>Connaissances</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getJoueur()
 * @model
 * @generated
 */
public interface Joueur extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getJoueur_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Joueur#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Limite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Limite</em>' attribute.
   * @see #setLimite(int)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getJoueur_Limite()
   * @model
   * @generated
   */
  int getLimite();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Joueur#getLimite <em>Limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Limite</em>' attribute.
   * @see #getLimite()
   * @generated
   */
  void setLimite(int value);

  /**
   * Returns the value of the '<em><b>Objets</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.eNIGMA.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets</em>' containment reference list.
   * @see fr.n7.eNIGMA.ENIGMAPackage#getJoueur_Objets()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjets();

  /**
   * Returns the value of the '<em><b>Connaissances</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.eNIGMA.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissances</em>' containment reference list.
   * @see fr.n7.eNIGMA.ENIGMAPackage#getJoueur_Connaissances()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getConnaissances();

} // Joueur
