/**
 * generated by Xtext 2.23.0
 */
package fr.n7.eNIGMA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lieu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Lieu#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Lieu#getPersonne <em>Personne</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getLieu()
 * @model
 * @generated
 */
public interface Lieu extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getLieu_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Lieu#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Personne</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Personne</em>' containment reference.
   * @see #setPersonne(Personne)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getLieu_Personne()
   * @model containment="true"
   * @generated
   */
  Personne getPersonne();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Lieu#getPersonne <em>Personne</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Personne</em>' containment reference.
   * @see #getPersonne()
   * @generated
   */
  void setPersonne(Personne value);

} // Lieu
