/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Personne</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Personne#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Personne#getEtato <em>Etato</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Personne#getConditiono <em>Conditiono</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Personne#getEtatv <em>Etatv</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Personne#getConditionv <em>Conditionv</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Personne#getTexte <em>Texte</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Personne#getInteraction <em>Interaction</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getPersonne()
 * @model
 * @generated
 */
public interface Personne extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getPersonne_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Personne#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Etato</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.eNIGMA.EtatObligation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Etato</em>' attribute.
   * @see fr.n7.eNIGMA.EtatObligation
   * @see #setEtato(EtatObligation)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getPersonne_Etato()
   * @model
   * @generated
   */
  EtatObligation getEtato();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Personne#getEtato <em>Etato</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Etato</em>' attribute.
   * @see fr.n7.eNIGMA.EtatObligation
   * @see #getEtato()
   * @generated
   */
  void setEtato(EtatObligation value);

  /**
   * Returns the value of the '<em><b>Conditiono</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditiono</em>' reference.
   * @see #setConditiono(Condition)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getPersonne_Conditiono()
   * @model
   * @generated
   */
  Condition getConditiono();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Personne#getConditiono <em>Conditiono</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditiono</em>' reference.
   * @see #getConditiono()
   * @generated
   */
  void setConditiono(Condition value);

  /**
   * Returns the value of the '<em><b>Etatv</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.eNIGMA.EtatVisibilite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Etatv</em>' attribute.
   * @see fr.n7.eNIGMA.EtatVisibilite
   * @see #setEtatv(EtatVisibilite)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getPersonne_Etatv()
   * @model
   * @generated
   */
  EtatVisibilite getEtatv();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Personne#getEtatv <em>Etatv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Etatv</em>' attribute.
   * @see fr.n7.eNIGMA.EtatVisibilite
   * @see #getEtatv()
   * @generated
   */
  void setEtatv(EtatVisibilite value);

  /**
   * Returns the value of the '<em><b>Conditionv</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditionv</em>' reference.
   * @see #setConditionv(Condition)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getPersonne_Conditionv()
   * @model
   * @generated
   */
  Condition getConditionv();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Personne#getConditionv <em>Conditionv</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditionv</em>' reference.
   * @see #getConditionv()
   * @generated
   */
  void setConditionv(Condition value);

  /**
   * Returns the value of the '<em><b>Texte</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texte</em>' containment reference.
   * @see #setTexte(Qualification)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getPersonne_Texte()
   * @model containment="true"
   * @generated
   */
  Qualification getTexte();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Personne#getTexte <em>Texte</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texte</em>' containment reference.
   * @see #getTexte()
   * @generated
   */
  void setTexte(Qualification value);

  /**
   * Returns the value of the '<em><b>Interaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interaction</em>' containment reference.
   * @see #setInteraction(Interaction)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getPersonne_Interaction()
   * @model containment="true"
   * @generated
   */
  Interaction getInteraction();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Personne#getInteraction <em>Interaction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interaction</em>' containment reference.
   * @see #getInteraction()
   * @generated
   */
  void setInteraction(Interaction value);

} // Personne
