/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Qualification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Qualification#getQualification <em>Qualification</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getQualification()
 * @model
 * @generated
 */
public interface Qualification extends EObject
{
  /**
   * Returns the value of the '<em><b>Qualification</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualification</em>' attribute.
   * @see #setQualification(String)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getQualification_Qualification()
   * @model
   * @generated
   */
  String getQualification();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Qualification#getQualification <em>Qualification</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qualification</em>' attribute.
   * @see #getQualification()
   * @generated
   */
  void setQualification(String value);

} // Qualification
