/**
 * generated by Xtext 2.23.0
 */
package fr.n7.eNIGMA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reponse</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.Reponse#getTexte <em>Texte</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.Reponse#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see fr.n7.eNIGMA.ENIGMAPackage#getReponse()
 * @model
 * @generated
 */
public interface Reponse extends EObject
{
  /**
   * Returns the value of the '<em><b>Texte</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texte</em>' containment reference.
   * @see #setTexte(Qualification)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getReponse_Texte()
   * @model containment="true"
   * @generated
   */
  Qualification getTexte();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Reponse#getTexte <em>Texte</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texte</em>' containment reference.
   * @see #getTexte()
   * @generated
   */
  void setTexte(Qualification value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(Action)
   * @see fr.n7.eNIGMA.ENIGMAPackage#getReponse_Action()
   * @model containment="true"
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link fr.n7.eNIGMA.Reponse#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

} // Reponse
