/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.enigma.ui.internal.EnigmaActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ENIGMAUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EnigmaActivator.getInstance().getInjector("fr.n7.ENIGMA");
	}

}
