/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA.impl;

import fr.n7.eNIGMA.Connaissance;
import fr.n7.eNIGMA.ENIGMAPackage;
import fr.n7.eNIGMA.EtatPossession;
import fr.n7.eNIGMA.EtatVisibilite;
import fr.n7.eNIGMA.Qualification;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Connaissance</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.impl.ConnaissanceImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.ConnaissanceImpl#getQualification <em>Qualification</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.ConnaissanceImpl#getEtatv <em>Etatv</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.ConnaissanceImpl#getEtatp <em>Etatp</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConnaissanceImpl extends JeuElementImpl implements Connaissance
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getQualification() <em>Qualification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQualification()
   * @generated
   * @ordered
   */
  protected Qualification qualification;

  /**
   * The default value of the '{@link #getEtatv() <em>Etatv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEtatv()
   * @generated
   * @ordered
   */
  protected static final EtatVisibilite ETATV_EDEFAULT = EtatVisibilite.VISIBLE;

  /**
   * The cached value of the '{@link #getEtatv() <em>Etatv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEtatv()
   * @generated
   * @ordered
   */
  protected EtatVisibilite etatv = ETATV_EDEFAULT;

  /**
   * The default value of the '{@link #getEtatp() <em>Etatp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEtatp()
   * @generated
   * @ordered
   */
  protected static final EtatPossession ETATP_EDEFAULT = EtatPossession.POSSEDE;

  /**
   * The cached value of the '{@link #getEtatp() <em>Etatp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEtatp()
   * @generated
   * @ordered
   */
  protected EtatPossession etatp = ETATP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnaissanceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ENIGMAPackage.Literals.CONNAISSANCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.CONNAISSANCE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Qualification getQualification()
  {
    return qualification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetQualification(Qualification newQualification, NotificationChain msgs)
  {
    Qualification oldQualification = qualification;
    qualification = newQualification;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ENIGMAPackage.CONNAISSANCE__QUALIFICATION, oldQualification, newQualification);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQualification(Qualification newQualification)
  {
    if (newQualification != qualification)
    {
      NotificationChain msgs = null;
      if (qualification != null)
        msgs = ((InternalEObject)qualification).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.CONNAISSANCE__QUALIFICATION, null, msgs);
      if (newQualification != null)
        msgs = ((InternalEObject)newQualification).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.CONNAISSANCE__QUALIFICATION, null, msgs);
      msgs = basicSetQualification(newQualification, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.CONNAISSANCE__QUALIFICATION, newQualification, newQualification));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EtatVisibilite getEtatv()
  {
    return etatv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEtatv(EtatVisibilite newEtatv)
  {
    EtatVisibilite oldEtatv = etatv;
    etatv = newEtatv == null ? ETATV_EDEFAULT : newEtatv;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.CONNAISSANCE__ETATV, oldEtatv, etatv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EtatPossession getEtatp()
  {
    return etatp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEtatp(EtatPossession newEtatp)
  {
    EtatPossession oldEtatp = etatp;
    etatp = newEtatp == null ? ETATP_EDEFAULT : newEtatp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.CONNAISSANCE__ETATP, oldEtatp, etatp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ENIGMAPackage.CONNAISSANCE__QUALIFICATION:
        return basicSetQualification(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ENIGMAPackage.CONNAISSANCE__NAME:
        return getName();
      case ENIGMAPackage.CONNAISSANCE__QUALIFICATION:
        return getQualification();
      case ENIGMAPackage.CONNAISSANCE__ETATV:
        return getEtatv();
      case ENIGMAPackage.CONNAISSANCE__ETATP:
        return getEtatp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ENIGMAPackage.CONNAISSANCE__NAME:
        setName((String)newValue);
        return;
      case ENIGMAPackage.CONNAISSANCE__QUALIFICATION:
        setQualification((Qualification)newValue);
        return;
      case ENIGMAPackage.CONNAISSANCE__ETATV:
        setEtatv((EtatVisibilite)newValue);
        return;
      case ENIGMAPackage.CONNAISSANCE__ETATP:
        setEtatp((EtatPossession)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ENIGMAPackage.CONNAISSANCE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ENIGMAPackage.CONNAISSANCE__QUALIFICATION:
        setQualification((Qualification)null);
        return;
      case ENIGMAPackage.CONNAISSANCE__ETATV:
        setEtatv(ETATV_EDEFAULT);
        return;
      case ENIGMAPackage.CONNAISSANCE__ETATP:
        setEtatp(ETATP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ENIGMAPackage.CONNAISSANCE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ENIGMAPackage.CONNAISSANCE__QUALIFICATION:
        return qualification != null;
      case ENIGMAPackage.CONNAISSANCE__ETATV:
        return etatv != ETATV_EDEFAULT;
      case ENIGMAPackage.CONNAISSANCE__ETATP:
        return etatp != ETATP_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", etatv: ");
    result.append(etatv);
    result.append(", etatp: ");
    result.append(etatp);
    result.append(')');
    return result.toString();
  }

} //ConnaissanceImpl
