/**
 * generated by Xtext 2.23.0
 */
package fr.n7.eNIGMA.impl;

import fr.n7.eNIGMA.ENIGMAPackage;
import fr.n7.eNIGMA.Jeu;
import fr.n7.eNIGMA.Joueur;
import fr.n7.eNIGMA.Territoire;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Jeu</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.impl.JeuImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.JeuImpl#getTerritoire <em>Territoire</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.JeuImpl#getJoueur <em>Joueur</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JeuImpl extends MinimalEObjectImpl.Container implements Jeu
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTerritoire() <em>Territoire</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerritoire()
   * @generated
   * @ordered
   */
  protected Territoire territoire;

  /**
   * The cached value of the '{@link #getJoueur() <em>Joueur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJoueur()
   * @generated
   * @ordered
   */
  protected Joueur joueur;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JeuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ENIGMAPackage.Literals.JEU;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.JEU__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Territoire getTerritoire()
  {
    return territoire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTerritoire(Territoire newTerritoire, NotificationChain msgs)
  {
    Territoire oldTerritoire = territoire;
    territoire = newTerritoire;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ENIGMAPackage.JEU__TERRITOIRE, oldTerritoire, newTerritoire);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTerritoire(Territoire newTerritoire)
  {
    if (newTerritoire != territoire)
    {
      NotificationChain msgs = null;
      if (territoire != null)
        msgs = ((InternalEObject)territoire).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.JEU__TERRITOIRE, null, msgs);
      if (newTerritoire != null)
        msgs = ((InternalEObject)newTerritoire).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.JEU__TERRITOIRE, null, msgs);
      msgs = basicSetTerritoire(newTerritoire, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.JEU__TERRITOIRE, newTerritoire, newTerritoire));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Joueur getJoueur()
  {
    return joueur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetJoueur(Joueur newJoueur, NotificationChain msgs)
  {
    Joueur oldJoueur = joueur;
    joueur = newJoueur;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ENIGMAPackage.JEU__JOUEUR, oldJoueur, newJoueur);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJoueur(Joueur newJoueur)
  {
    if (newJoueur != joueur)
    {
      NotificationChain msgs = null;
      if (joueur != null)
        msgs = ((InternalEObject)joueur).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.JEU__JOUEUR, null, msgs);
      if (newJoueur != null)
        msgs = ((InternalEObject)newJoueur).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.JEU__JOUEUR, null, msgs);
      msgs = basicSetJoueur(newJoueur, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.JEU__JOUEUR, newJoueur, newJoueur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ENIGMAPackage.JEU__TERRITOIRE:
        return basicSetTerritoire(null, msgs);
      case ENIGMAPackage.JEU__JOUEUR:
        return basicSetJoueur(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ENIGMAPackage.JEU__NAME:
        return getName();
      case ENIGMAPackage.JEU__TERRITOIRE:
        return getTerritoire();
      case ENIGMAPackage.JEU__JOUEUR:
        return getJoueur();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ENIGMAPackage.JEU__NAME:
        setName((String)newValue);
        return;
      case ENIGMAPackage.JEU__TERRITOIRE:
        setTerritoire((Territoire)newValue);
        return;
      case ENIGMAPackage.JEU__JOUEUR:
        setJoueur((Joueur)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ENIGMAPackage.JEU__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ENIGMAPackage.JEU__TERRITOIRE:
        setTerritoire((Territoire)null);
        return;
      case ENIGMAPackage.JEU__JOUEUR:
        setJoueur((Joueur)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ENIGMAPackage.JEU__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ENIGMAPackage.JEU__TERRITOIRE:
        return territoire != null;
      case ENIGMAPackage.JEU__JOUEUR:
        return joueur != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //JeuImpl
