/**
 * generated by Xtext 2.25.0
 */
package fr.n7.eNIGMA.impl;

import fr.n7.eNIGMA.Condition;
import fr.n7.eNIGMA.ENIGMAPackage;
import fr.n7.eNIGMA.EtatObligation;
import fr.n7.eNIGMA.EtatVisibilite;
import fr.n7.eNIGMA.Interaction;
import fr.n7.eNIGMA.Personne;
import fr.n7.eNIGMA.Qualification;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Personne</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.eNIGMA.impl.PersonneImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.PersonneImpl#getEtato <em>Etato</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.PersonneImpl#getConditiono <em>Conditiono</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.PersonneImpl#getEtatv <em>Etatv</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.PersonneImpl#getConditionv <em>Conditionv</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.PersonneImpl#getTexte <em>Texte</em>}</li>
 *   <li>{@link fr.n7.eNIGMA.impl.PersonneImpl#getInteraction <em>Interaction</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PersonneImpl extends JeuElementImpl implements Personne
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getEtato() <em>Etato</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEtato()
   * @generated
   * @ordered
   */
  protected static final EtatObligation ETATO_EDEFAULT = EtatObligation.OBLIGATOIRE;

  /**
   * The cached value of the '{@link #getEtato() <em>Etato</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEtato()
   * @generated
   * @ordered
   */
  protected EtatObligation etato = ETATO_EDEFAULT;

  /**
   * The cached value of the '{@link #getConditiono() <em>Conditiono</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditiono()
   * @generated
   * @ordered
   */
  protected Condition conditiono;

  /**
   * The default value of the '{@link #getEtatv() <em>Etatv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEtatv()
   * @generated
   * @ordered
   */
  protected static final EtatVisibilite ETATV_EDEFAULT = EtatVisibilite.VISIBLE;

  /**
   * The cached value of the '{@link #getEtatv() <em>Etatv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEtatv()
   * @generated
   * @ordered
   */
  protected EtatVisibilite etatv = ETATV_EDEFAULT;

  /**
   * The cached value of the '{@link #getConditionv() <em>Conditionv</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionv()
   * @generated
   * @ordered
   */
  protected Condition conditionv;

  /**
   * The cached value of the '{@link #getTexte() <em>Texte</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTexte()
   * @generated
   * @ordered
   */
  protected Qualification texte;

  /**
   * The cached value of the '{@link #getInteraction() <em>Interaction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteraction()
   * @generated
   * @ordered
   */
  protected Interaction interaction;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersonneImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ENIGMAPackage.Literals.PERSONNE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EtatObligation getEtato()
  {
    return etato;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEtato(EtatObligation newEtato)
  {
    EtatObligation oldEtato = etato;
    etato = newEtato == null ? ETATO_EDEFAULT : newEtato;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__ETATO, oldEtato, etato));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Condition getConditiono()
  {
    if (conditiono != null && conditiono.eIsProxy())
    {
      InternalEObject oldConditiono = (InternalEObject)conditiono;
      conditiono = (Condition)eResolveProxy(oldConditiono);
      if (conditiono != oldConditiono)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ENIGMAPackage.PERSONNE__CONDITIONO, oldConditiono, conditiono));
      }
    }
    return conditiono;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Condition basicGetConditiono()
  {
    return conditiono;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConditiono(Condition newConditiono)
  {
    Condition oldConditiono = conditiono;
    conditiono = newConditiono;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__CONDITIONO, oldConditiono, conditiono));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EtatVisibilite getEtatv()
  {
    return etatv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEtatv(EtatVisibilite newEtatv)
  {
    EtatVisibilite oldEtatv = etatv;
    etatv = newEtatv == null ? ETATV_EDEFAULT : newEtatv;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__ETATV, oldEtatv, etatv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Condition getConditionv()
  {
    if (conditionv != null && conditionv.eIsProxy())
    {
      InternalEObject oldConditionv = (InternalEObject)conditionv;
      conditionv = (Condition)eResolveProxy(oldConditionv);
      if (conditionv != oldConditionv)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ENIGMAPackage.PERSONNE__CONDITIONV, oldConditionv, conditionv));
      }
    }
    return conditionv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Condition basicGetConditionv()
  {
    return conditionv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConditionv(Condition newConditionv)
  {
    Condition oldConditionv = conditionv;
    conditionv = newConditionv;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__CONDITIONV, oldConditionv, conditionv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Qualification getTexte()
  {
    return texte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTexte(Qualification newTexte, NotificationChain msgs)
  {
    Qualification oldTexte = texte;
    texte = newTexte;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__TEXTE, oldTexte, newTexte);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTexte(Qualification newTexte)
  {
    if (newTexte != texte)
    {
      NotificationChain msgs = null;
      if (texte != null)
        msgs = ((InternalEObject)texte).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.PERSONNE__TEXTE, null, msgs);
      if (newTexte != null)
        msgs = ((InternalEObject)newTexte).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.PERSONNE__TEXTE, null, msgs);
      msgs = basicSetTexte(newTexte, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__TEXTE, newTexte, newTexte));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interaction getInteraction()
  {
    return interaction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInteraction(Interaction newInteraction, NotificationChain msgs)
  {
    Interaction oldInteraction = interaction;
    interaction = newInteraction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__INTERACTION, oldInteraction, newInteraction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInteraction(Interaction newInteraction)
  {
    if (newInteraction != interaction)
    {
      NotificationChain msgs = null;
      if (interaction != null)
        msgs = ((InternalEObject)interaction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.PERSONNE__INTERACTION, null, msgs);
      if (newInteraction != null)
        msgs = ((InternalEObject)newInteraction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ENIGMAPackage.PERSONNE__INTERACTION, null, msgs);
      msgs = basicSetInteraction(newInteraction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ENIGMAPackage.PERSONNE__INTERACTION, newInteraction, newInteraction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ENIGMAPackage.PERSONNE__TEXTE:
        return basicSetTexte(null, msgs);
      case ENIGMAPackage.PERSONNE__INTERACTION:
        return basicSetInteraction(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ENIGMAPackage.PERSONNE__NAME:
        return getName();
      case ENIGMAPackage.PERSONNE__ETATO:
        return getEtato();
      case ENIGMAPackage.PERSONNE__CONDITIONO:
        if (resolve) return getConditiono();
        return basicGetConditiono();
      case ENIGMAPackage.PERSONNE__ETATV:
        return getEtatv();
      case ENIGMAPackage.PERSONNE__CONDITIONV:
        if (resolve) return getConditionv();
        return basicGetConditionv();
      case ENIGMAPackage.PERSONNE__TEXTE:
        return getTexte();
      case ENIGMAPackage.PERSONNE__INTERACTION:
        return getInteraction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ENIGMAPackage.PERSONNE__NAME:
        setName((String)newValue);
        return;
      case ENIGMAPackage.PERSONNE__ETATO:
        setEtato((EtatObligation)newValue);
        return;
      case ENIGMAPackage.PERSONNE__CONDITIONO:
        setConditiono((Condition)newValue);
        return;
      case ENIGMAPackage.PERSONNE__ETATV:
        setEtatv((EtatVisibilite)newValue);
        return;
      case ENIGMAPackage.PERSONNE__CONDITIONV:
        setConditionv((Condition)newValue);
        return;
      case ENIGMAPackage.PERSONNE__TEXTE:
        setTexte((Qualification)newValue);
        return;
      case ENIGMAPackage.PERSONNE__INTERACTION:
        setInteraction((Interaction)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ENIGMAPackage.PERSONNE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ENIGMAPackage.PERSONNE__ETATO:
        setEtato(ETATO_EDEFAULT);
        return;
      case ENIGMAPackage.PERSONNE__CONDITIONO:
        setConditiono((Condition)null);
        return;
      case ENIGMAPackage.PERSONNE__ETATV:
        setEtatv(ETATV_EDEFAULT);
        return;
      case ENIGMAPackage.PERSONNE__CONDITIONV:
        setConditionv((Condition)null);
        return;
      case ENIGMAPackage.PERSONNE__TEXTE:
        setTexte((Qualification)null);
        return;
      case ENIGMAPackage.PERSONNE__INTERACTION:
        setInteraction((Interaction)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ENIGMAPackage.PERSONNE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ENIGMAPackage.PERSONNE__ETATO:
        return etato != ETATO_EDEFAULT;
      case ENIGMAPackage.PERSONNE__CONDITIONO:
        return conditiono != null;
      case ENIGMAPackage.PERSONNE__ETATV:
        return etatv != ETATV_EDEFAULT;
      case ENIGMAPackage.PERSONNE__CONDITIONV:
        return conditionv != null;
      case ENIGMAPackage.PERSONNE__TEXTE:
        return texte != null;
      case ENIGMAPackage.PERSONNE__INTERACTION:
        return interaction != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", etato: ");
    result.append(etato);
    result.append(", etatv: ");
    result.append(etatv);
    result.append(')');
    return result.toString();
  }

} //PersonneImpl
